# Get ingo about GPU

In [7]:
gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Not connected to a GPU')
else:
  print(gpu_info)

Wed Oct 19 07:41:05 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P0    29W /  70W |    610MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [8]:
from psutil import virtual_memory
ram_gb = virtual_memory().total / 1e9
print('Your runtime has {:.1f} gigabytes of available RAM\n'.format(ram_gb))

if ram_gb < 20:
  print('Not using a high-RAM runtime')
else:
  print('You are using a high-RAM runtime!')

Your runtime has 27.3 gigabytes of available RAM

You are using a high-RAM runtime!


# Import usefull packages

In [9]:
from torch.utils.data import Dataset
import torchaudio
import torch

from google.colab import drive

from random import shuffle
import numpy as np

from torch.functional import Tensor

import torch.nn as nn
import torch.nn.functional as F

import torch.optim as optim

import matplotlib.pyplot as plt

# Check an accessibility of the GPU

In [10]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print(device)

cuda:0


# Loading data

In [11]:
drive.mount('/content/drive')
eps = 1e-4
SAMPLE_RATE = 16000
nFFt = 512
winLength = 512
hopLength = 256
nMels = 64


def normalize(data):
    mean, std, var = torch.mean(data), torch.std(data), torch.var(data)
    data = (data-mean)/std
    return data


class UploadArtificialDataset(Dataset):
    def __init__(self, file_with_paths, file_with_references, transformation, target_sample_rate, device):
        self.paths = self.loader(file_with_paths)
        self.references = self.loader(file_with_references)
        self.device = device
        self.transformation = transformation.to(self.device)
        self.transformation = transformation
        self.target_sample_rate = target_sample_rate
      
    
    def loader(self, path):
        paths = []
        with open(path, "r") as file:
            for line in file:
                paths.append(line[0:len(line)-1])
        return paths


    def __len__(self):
        return len(self.paths)


    def __getitem__(self, index):
        # sr - sample rate
        signal, sr = torchaudio.load("/content/drive/My Drive/artificial" + self.paths[index])
        signal = signal.to(self.device)

        signal = normalize(signal)
        signal = self.transformation(signal)
        signal = signal + eps
        signal = 10*torch.log10(signal)
        
        references = self.references[index]
        ref = []
        ref = references.split("|")
        return signal, ref


if __name__ == "__main__":
    paths_file = "/content/drive/My Drive/artificial/pathsToTrainSounds.txt"
    references = "/content/drive/My Drive/artificial/trainRef.txt"

    spectrogram = torchaudio.transforms.MelSpectrogram(
        sample_rate=SAMPLE_RATE,
        n_fft=nFFt,
        win_length = winLength,
        hop_length = hopLength,
        n_mels = nMels,
        power=1,
        normalized=True
    )
    
    uad = UploadArtificialDataset(paths_file, references, spectrogram, SAMPLE_RATE, device)

    print(f"There are {len(uad)} samples in the dataset.")
    signal, ref = uad[34000]
    print(signal.shape)
    print(ref)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
There are 150684 samples in the dataset.
torch.Size([1, 64, 126])
['19.4', '20.6']


# Irreplaceable functions


In [ ]:
# Mix data function

def mix_data(uad):
  indexes = []
  indexes.extend(range(0, len(uad) - 1))
  shuffle(indexes)
  return indexes

In [ ]:
def clever_gener_chunk(ind, uad, ONESECMODE=False, n_minibatches=300):
    chunk = []
    references = []
    memory = 0
    for i in range(0, len(ind)):
        minibatch = torch.zeros(100, nMels, int(16000 / hopLength))
        ref = []
        if not ONESECMODE:
            start, finish = 0, 0
            for j in range(memory, len(ind)):
                signal, refer = uad[ind[j]]
                m = int(signal.shape[2]/int(16000 / hopLength))
                finish = finish + m
                if finish > 99:
                    m = m - (finish - 100)
                    finish = 99
                move = 0
                for k in range(m):
                    minibatch[start + k] = signal[:, 0:nMels,0+move:int(16000 / hopLength)+move]
                    move = move + int(16000 / hopLength)
                    ref.append(refer[k])
                start = finish
                if len(ref) == 100:
                    chunk.append(minibatch)
                    references.append(ref)
                    memory = j + 1
                    break
                if j == (len(ind) - 1):
                    return chunk, references
        else:
            if len(ind)==1:
                signal, refer = uad[ind[0]]
                for j in range(100):
                    minibatch[j] = signal[:, 0:nMels, 0:int(16000 / hopLength)]
                    ref.append(refer[0])
                chunk.append(minibatch)
                references.append(ref)
                return chunk, references
            elif len(ind)==2:
                signal, refer = uad[ind[0]]
                signal2, refer2 = uad[ind[1]]
                ii = []
                ii.extend(range(0, 100))
                for j in range(0, len(ii), 2):
                    minibatch[j] = signal[:, 0:nMels, 0:int(16000 / hopLength)]
                    minibatch[j+1] = signal2[:, 0:nMels, 0:int(16000 / hopLength)]
                    ref.append(refer[0])
                    ref.append(refer2[0])
                chunk.append(minibatch)
                references.append(ref)
                return chunk, references
        if i == n_minibatches-1:
            break
    return chunk, references

indexes = [[1, 9000, 70000, 10000, 256, 98786, 10256, 84589, 129, 17, 65000, 680, 999, 90900, 280, 50000,34000, 1356, 65,
            876, 10278, 59376, 20984, 47250, 51600, 85395, 90000], [50], [150000, 2]]
s, k = clever_gener_chunk(indexes[2], uad, ONESECMODE=True, n_minibatches=0)
print('NUMBER OF MINIBATCHES', [len(a) for a in s])
print('NUMBER OF REFERENCES', [len(a) for a in k])
print('TENSOR [0] shape:', s[0].shape)
print('REFERENCE [0] len:', len(k[0]))
print(s[0][0][0][1])
print(s[0][1][0][1])
print(s[0][10][0][1])
print("...")

NUMBER OF MINIBATCHES [100]
NUMBER OF REFERENCES [100]
TENSOR [0] shape: torch.Size([100, 64, 62])
REFERENCE [0] len: 100
tensor(9.5864)
tensor(-0.2869)
tensor(9.5864)
...


# Definition of the network 

In [ ]:
class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 32, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(32, 32, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv3 = nn.Conv2d(32, 32, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.fc1 = nn.Linear(512, 256)
        self.fc2 = nn.Linear(256, 1)
        # 1 -> 6

    def forward(self, x):
        x = self.pool(F.elu(self.conv1(x)))
        # print('1. vrstva',x.shape)
        x = self.pool(F.elu(self.conv2(x)))
        # print('2. vrstva',x.shape)
        x = self.pool(F.elu(self.conv3(x)))
        # print('3. vrstva',x.shape)
        # x = self.pool(F.elu(self.conv4(x)))
        # print('4. vrstva',x.shape)
        # x = torch.flatten(x, 1) # flatten all
        x = x.view(x.size(0), -1)
        # print('po flatten', x.shape)
        x = F.elu(self.fc1(x))
        x = self.fc2(x)
        return x

In [ ]:
net = Net()

# If we want to train the network from the beginning, we must also run next code cell

In [ ]:
# Creation of indexes
indexes = mix_data(uad)
indexes = np.reshape(indexes, (173, -1))
indexes = torch.Tensor(indexes).int()

# Saving of created indexes
torch.save(indexes, '/content/drive/My Drive/artificial/indexes.pt')

# Saving of zero number of chunk
number = 0
torch.save(number, '/content/drive/My Drive/artificial/numberOfChunk.pt')

# Saving a base model
torch.save(net.state_dict(), "/content/drive/My Drive/artificial/modelka.pth")

# Next part of the code is always run, regardless of the type of network training

In [ ]:
# Loading a model
net.load_state_dict(torch.load("/content/drive/My Drive/artificial/modelka.pth"))
net.eval()

# Loading indexes
indexes = torch.load('/content/drive/My Drive/artificial/indexes.pt')

# Loading a number og chunk
number = torch.load('/content/drive/My Drive/artificial/numberOfChunk.pt')

In [ ]:
# Definition of a Loss function and optimizer
loss_epoch = nn.MSELoss()
optimizer = optim.Adam(net.parameters(), lr=0.01)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min',
    factor=0.1, patience=2, threshold=0.001, threshold_mode='abs')

In [ ]:
# Print model's state_dict
print("Model's state_dict:")
for param_tensor in net.state_dict():
    print(param_tensor, "\t", net.state_dict()[param_tensor].size())

# Print optimizer's state_dict
print("Optimizer's state_dict:")
for var_name in optimizer.state_dict():
    print(var_name, "\t", optimizer.state_dict()[var_name])

Model's state_dict:
conv1.weight 	 torch.Size([32, 1, 5, 5])
conv1.bias 	 torch.Size([32])
conv2.weight 	 torch.Size([32, 32, 5, 5])
conv2.bias 	 torch.Size([32])
conv3.weight 	 torch.Size([32, 32, 5, 5])
conv3.bias 	 torch.Size([32])
fc1.weight 	 torch.Size([256, 512])
fc1.bias 	 torch.Size([256])
fc2.weight 	 torch.Size([1, 256])
fc2.bias 	 torch.Size([1])
Optimizer's state_dict:
state 	 {}
param_groups 	 [{'lr': 0.01, 'betas': (0.9, 0.999), 'eps': 1e-08, 'weight_decay': 0, 'amsgrad': False, 'maximize': False, 'foreach': None, 'capturable': False, 'params': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]}]


In [ ]:
# sent network to the device
net.to(device)

Net(
  (conv1): Conv2d(1, 32, kernel_size=(5, 5), stride=(1, 1))
  (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(32, 32, kernel_size=(5, 5), stride=(1, 1))
  (conv3): Conv2d(32, 32, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=512, out_features=256, bias=True)
  (fc2): Linear(in_features=256, out_features=1, bias=True)
)

# Training of the network

In [ ]:
# number = 0
# indexes = [[121320, 62163, 76200, 141837, 129434, 79293, 27418, 139727, 128900],
#            [121320, 62163, 76200, 141837, 129434, 79293, 27418, 139727, 128900],
#            [121320, 62163, 76200, 141837, 129434, 79293, 27418, 139727, 128900],
#            [121320, 62163, 76200, 141837, 129434, 79293, 27418, 139727, 128900]]

# indexes = [[150000, 150001]]
# print(indexes[0])
# start = torch.cuda.Event(enable_timing=True)
# end = torch.cuda.Event(enable_timing=True)

# start.record()

if device.__eq__('cuda:0'):
    for epoch in range(500):
        number = torch.load('/content/drive/My Drive/artificial/numberOfChunk.pt')
        for ch in range(number, len(indexes)):
            chunk, reference = clever_gener_chunk(indexes[ch], uad, ONESECMODE=False, n_minibatches=30)
            running_loss = 0.0
            for i in range(0, len(chunk)):
                inputs, labels = chunk[i], reference[i]
                labels = list(map(float, labels))
                labels = torch.FloatTensor(labels)
                labels = labels.to(device)
                inputs = inputs[None, :, :, :]
                inputs = torch.permute(inputs, (1, 0, 2, 3))
                inputs = inputs.to(device)
                # forward + backward + optimize
                outputs = net(inputs)
                loss = loss_epoch(outputs, labels)
                optimizer.zero_grad()
                loss.backward()
                # torch.nn.utils.clip_grad_norm_(net.parameters(), 5)
                optimizer.step()
                running_loss += loss.item()
            print(f'[{epoch + 1}, {len(chunk)}] loss: {running_loss / len(chunk)}')
            torch.save(ch, '/content/drive/My Drive/artificial/numberOfChunk.pt')
            # vl_loss = validate(loss)
            scheduler.step(running_loss)
            print(scheduler.state_dict())
            if (running_loss/len(chunk) == 0):
                break
        if (running_loss/len(chunk) == 0):
                break
        indexes = np.concatenate(indexes)
        shuffle(indexes)
        indexes = np.reshape(indexes, (173, -1))
        ch = 0
        torch.save(ch, '/content/drive/My Drive/artificial/numberOfChunk.pt')
        torch.save(net.state_dict(), "/content/drive/My Drive/artificial/modelka.pth")
    print('Finished Training')
else:
  print('Traning wasnt started, due to unavailabile cuda device')

# end.record()

[1, 30] loss: 4486.52193959554
{'factor': 0.1, 'min_lrs': [0], 'patience': 2, 'verbose': False, 'cooldown': 0, 'cooldown_counter': 0, 'mode': 'min', 'threshold': 0.001, 'threshold_mode': 'abs', 'best': 279.1319885253906, 'num_bad_epochs': 0, 'mode_worse': inf, 'eps': 1e-08, 'last_epoch': 1, '_last_lr': [0.01]}
[1, 30] loss: 411.7732882181803
{'factor': 0.1, 'min_lrs': [0], 'patience': 2, 'verbose': False, 'cooldown': 0, 'cooldown_counter': 0, 'mode': 'min', 'threshold': 0.001, 'threshold_mode': 'abs', 'best': 279.1319885253906, 'num_bad_epochs': 1, 'mode_worse': inf, 'eps': 1e-08, 'last_epoch': 2, '_last_lr': [0.01]}
[1, 30] loss: 396.2837895711263
{'factor': 0.1, 'min_lrs': [0], 'patience': 2, 'verbose': False, 'cooldown': 0, 'cooldown_counter': 0, 'mode': 'min', 'threshold': 0.001, 'threshold_mode': 'abs', 'best': 279.1319885253906, 'num_bad_epochs': 2, 'mode_worse': inf, 'eps': 1e-08, 'last_epoch': 3, '_last_lr': [0.01]}
[1, 30] loss: 383.49131927490237
{'factor': 0.1, 'min_lrs': [0

KeyboardInterrupt: ignored

# Upload development data

In [ ]:
paths_file = "/content/drive/My Drive/artificial/pathsToDevelopSounds.txt"
references = "/content/drive/My Drive/artificial/developRef.txt"
spectrogram = torchaudio.transforms.MelSpectrogram(
    sample_rate=SAMPLE_RATE,
    n_fft=nFFt,
    win_length = winLength,
    hop_length = hopLength,
    n_mels = nMels,
    power=1,
    normalized=True
)

develop_uad = UploadArtificialDataset(paths_file, references, spectrogram, SAMPLE_RATE, device)

print(f"There are {len(develop_uad)} samples in the dataset.")
signal, ref = develop_uad[7924]
print(signal.shape)
print(ref)

There are 10272 samples in the dataset.
torch.Size([1, 64, 876])
['-1.2', '-0.5', '2.4', '-1.1', '-1.8', '-3.1', '3.1', '-1', '1.4', '0.6', '-3.8', '-4.6', '3.1', '2.4']


# Prepare&Predict functions

In [ ]:
# preparation function
def prepare_data(signal):
  len = int(signal.shape[2]/int(16000 / hopLength))
  prepared = torch.zeros(len, nMels, int(16000 / hopLength))
  move = 0
  for k in range(len):
    prepared[k] = signal[:, 0:nMels, 0+move:int(16000 / hopLength)+move]
    move = move + int(16000 / hopLength)
  prepared = prepared[None,:,:,:]
  prepared = torch.permute(prepared, (1,0,2,3))
  return prepared

# # ONE SECOND preparation
# def prepare_data(signal):
#   len = int(signal.shape[2]/int(16000 / hopLength))
#   prepared = torch.zeros(len, nMels, int(16000 / hopLength))
#   move = 0
#   for k in range(len):
#     prepared[k] = signal[:, 0:nMels, 0:int(16000 / hopLength)]
#   prepared = prepared[None,:,:,:]
#   prepared = torch.permute(prepared, (1,0,2,3))
#   return prepared


# prediction function
def predict(model, input, target):
    model.eval()
    with torch.no_grad():
        prediction = model(input)
    return prediction

# Testing of trained network

❗️**NEED TO BE MODIFIED**❗️

In [ ]:
def do_prediction(ind):
  s, r = uad[ind]
  s = prepare_data(s)
  s = s.to(device)

  r = list(map(float, r))
  # r = torch.ones(len(r))*r[0]
  r = torch.FloatTensor(r)
  print(r)
  r = r.to(device)

  return predict(net, s, r)

development_indexes = indexes[0]
for i in development_indexes[0:50]:
  print('-------------', i, '-------------')
  prediction = do_prediction(i).tolist()
  prediction = np.reshape(prediction, (1, -1))[0]
  prediction = torch.Tensor(prediction)
  print(prediction)

------------- tensor(47531, dtype=torch.int32) -------------
tensor([23.0000, 22.1000, 21.5000, 19.6000, 13.1000, 18.5000, 22.8000, 19.9000,
        16.0000, 19.2000, 19.0000, 17.0000, 15.3000, 24.9000, 20.6000])
tensor([-0.6232, -0.3148, -0.5404, -0.5570, -0.5506, -0.3406, -0.4479, -0.4510,
        -0.6395, -0.5586, -0.4764, -0.2788, -0.6270, -0.7402, -0.8412])
------------- tensor(84835, dtype=torch.int32) -------------
tensor([  1.8000,   6.6000,   3.6000,   1.6000,   1.2000,   1.7000,   1.1000,
         11.4000, -23.6000,  10.2000,   6.5000,  -1.4000,  -2.8000])
tensor([-0.3685, -0.4576, -0.4835, -0.2946, -0.5235, -0.5306, -0.3844, -0.4350,
        -0.4032,  0.1465, -0.2113, -0.1468, -0.1721])
------------- tensor(101998, dtype=torch.int32) -------------
tensor([ -0.7000,  -0.9000,   1.2000,  -6.4000,  -0.3000,   1.7000,  -3.2000,
          0.4000, -14.2000,   4.2000,   1.9000,   1.7000,  -0.5000,  -0.1000])
tensor([-0.2427, -0.1174, -0.2787, -0.2371, -0.1928, -0.2447, -0.2797, -0.

# GitHub access 

In [12]:
%cd /content/drive/MyDrive/artificial/
# Create NEW EMPTY folder
# !git init vik_prj
%cd vik_prj/

/content/drive/MyDrive/artificial
/content/drive/MyDrive/artificial/vik_prj


In [ ]:
%ls -a .git/

In [ ]:
!git status

On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   clear_project.ipynb

no changes added to commit (use "git add" and/or "git commit -a")


In [ ]:
!git add .

In [ ]:
!git config --global user.email "viktoriia.sergeeva@tul.cz"
!git config --global user.name "ViktoriiaSr"

In [ ]:
!git commit -m "Adding of test 1 and 2: one second, one file with same references"

[master afaa3c8] Adding of test 1 and 2: one second, one file with same references
 1 file changed, 1 insertion(+), 1 deletion(-)
 rewrite clear_project.ipynb (98%)


In [ ]:
username = "ViktoriiaSr"
repository = "vir_prj"
git_token = "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"

In [ ]:
!git remote add origin https://{git_token}@github.com/{username}/{repository}.git
!git remote -v

fatal: remote origin already exists.
origin	https://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@github.com/ViktoriiaSr/vir_prj.git (fetch)
origin	https://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@github.com/ViktoriiaSr/vir_prj.git (push)


In [ ]:
!git push -u origin master

Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 4.87 KiB | 1.22 MiB/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/ViktoriiaSr/vir_prj.git
   df93c3f..afaa3c8  master -> master
Branch 'master' set up to track remote branch 'master' from 'origin'.
