# Get ingo about GPU

In [71]:
gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Not connected to a GPU')
else:
  print(gpu_info)

Fri Sep  9 19:06:21 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P0    34W / 250W |   1023MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [72]:
from psutil import virtual_memory
ram_gb = virtual_memory().total / 1e9
print('Your runtime has {:.1f} gigabytes of available RAM\n'.format(ram_gb))

if ram_gb < 20:
  print('Not using a high-RAM runtime')
else:
  print('You are using a high-RAM runtime!')

Your runtime has 27.3 gigabytes of available RAM

You are using a high-RAM runtime!


# Import usefull packages

In [73]:
from torch.utils.data import Dataset
import torchaudio
import torch

from google.colab import drive

from random import shuffle
import numpy as np

from torch.functional import Tensor

import torch.nn as nn
import torch.nn.functional as F

import torch.optim as optim

import matplotlib.pyplot as plt

# Check an accessibility of the GPU

In [74]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print(device)

cuda:0


# Loading data

In [75]:
drive.mount('/content/drive')
eps = 1e-4
SAMPLE_RATE = 16000
nFFt = 512
winLength = 512
hopLength = 256
nMels = 64


def normalize(data):
  mean, std, var = torch.mean(data), torch.std(data), torch.var(data)
  data = (data-mean)/std
  return data


class UploadArtificialDataset(Dataset):
    def __init__(self, file_with_paths, file_with_references, transformation, target_sample_rate, device):
        self.paths = self.loader(file_with_paths)
        self.references = self.loader(file_with_references)
        self.device = device
        self.transformation = transformation.to(self.device)
        self.transformation = transformation
        self.target_sample_rate = target_sample_rate
      
    
    def loader(self, path):
        paths = []
        with open(path, "r") as file:
            for line in file:
                paths.append(line[0:len(line)-1])
        return paths


    def __len__(self):
        return len(self.paths)


    def __getitem__(self, index):
        # sr - sample rate
        signal, sr = torchaudio.load("/content/drive/My Drive/artificial" + self.paths[index])
        signal = signal.to(self.device)

        signal = normalize(signal)
        signal = self.transformation(signal)
        signal = signal + eps
        signal = 10*torch.log10(signal)
        
        references = self.references[index]
        ref = []
        ref = references.split("|")
        return signal, ref


if __name__ == "__main__":
    paths_file = "/content/drive/My Drive/artificial/pathsToTrainSounds.txt"
    references = "/content/drive/My Drive/artificial/trainRef.txt"

    spectrogram = torchaudio.transforms.MelSpectrogram(
        sample_rate=SAMPLE_RATE,
        n_fft=nFFt,
        win_length = winLength,
        hop_length = hopLength,
        n_mels = nMels,
        power=1,
        normalized=True
    )
    
    uad = UploadArtificialDataset(paths_file, references, spectrogram, SAMPLE_RATE, device)

    print(f"There are {len(uad)} samples in the dataset.")
    signal, ref = uad[34000]
    print(signal.shape)
    print(ref)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
There are 150684 samples in the dataset.
torch.Size([1, 64, 126])
['19.4', '20.6']


# Irreplaceable functions

❗ **DON'T FORGET TO UNCOMMENT SHUFFLE** ❗


In [76]:
# Mix data function

def mix_data(uad):
  indexes = []
  indexes.extend(range(0, len(uad) - 1))
  # shuffle(indexes)
  return indexes

In [77]:
# # Generate TEST chunk function One SECOND
# def generate_chunk(ind, uad):
#   chunk = []
#   references = []
#   ref = []
#   minibatch = torch.zeros(100, nMels, int(16000 / hopLength))
#   signal, refer = uad[ind]
#   for i in range(100):
#     minibatch[i] = signal[:, 0:nMels, 0:int(16000 / hopLength)]
#     ref.append(refer[0])
#   chunk.append(minibatch)
#   references.append(ref)
#   return chunk, references


# Generate TEST chunk function ONE FILE
def generate_chunk(ind, uad):
  chunk = []
  references = []
  minibatch = torch.zeros(100, nMels, int(16000 / hopLength))
  ref = []
  start = 0
  finish = 0
  for i in range(0, 100):
    signal, refer = uad[ind]
    m = int(signal.shape[2]/int(16000 / hopLength))
    finish = finish + m
    if finish > 99:
      m = m - (finish - 100)
      finish = 99
    move = 0
    for k in range(m):
      minibatch[start + k] = signal[:, 0:nMels, 0+move:int(16000 / hopLength)+move]
      move = move + int(16000 / hopLength)
      ref.append(refer[k])
    start = finish
    if len(ref) == 100:
      chunk.append(minibatch)
      references.append(ref)
      return chunk, references
  return chunk, references


s, k = generate_chunk(0, uad)
# print(s, k)
print(len(k[0]))
print(s[0].shape)
print(s[0][0])
print(s[0][14])
print(k[0])

100
torch.Size([100, 64, 62])
tensor([[ -1.0265,   0.8943,   1.2330,  ...,  -0.8396,   2.5370,   1.2308],
        [  3.3576,   3.3918,   3.7726,  ...,   3.0520,   4.4911,   3.6107],
        [  2.3431,   0.9038,   1.8724,  ...,   1.4404,   2.4256,   1.4917],
        ...,
        [-11.2978, -10.3950,  -9.7389,  ...,  -8.3744,  -9.6294, -10.5206],
        [ -9.9678, -10.1102,  -9.2541,  ...,  -5.8611,  -7.0694,  -8.4862],
        [-10.7931, -10.0565,  -9.5750,  ...,  -3.7895,  -5.5078,  -6.2681]])
tensor([[ -1.0265,   0.8943,   1.2330,  ...,  -0.8396,   2.5370,   1.2308],
        [  3.3576,   3.3918,   3.7726,  ...,   3.0520,   4.4911,   3.6107],
        [  2.3431,   0.9038,   1.8724,  ...,   1.4404,   2.4256,   1.4917],
        ...,
        [-11.2978, -10.3950,  -9.7389,  ...,  -8.3744,  -9.6294, -10.5206],
        [ -9.9678, -10.1102,  -9.2541,  ...,  -5.8611,  -7.0694,  -8.4862],
        [-10.7931, -10.0565,  -9.5750,  ...,  -3.7895,  -5.5078,  -6.2681]])
['50', '50', '50', '50', '50',

# Definition of the network 

In [78]:
class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 8, 5)
        self.pool = nn.MaxPool2d(2,2)
        self.conv2 = nn.Conv2d(8, 16, 5)
        self.pool = nn.MaxPool2d(2,2)
        self.conv3 = nn.Conv2d(16, 32, 5)
        self.pool = nn.MaxPool2d(2,2)
        self.fc1 = nn.Linear(512, 256)
        self.fc2 = nn.Linear(256, 1)
        # 1 -> 6
    def forward(self, x):
        x = self.pool(F.elu(self.conv1(x)))
        # print('1. vrstva',x.shape)
        x = self.pool(F.elu(self.conv2(x)))
        # print('2. vrstva',x.shape)
        x = self.pool(F.elu(self.conv3(x)))
        # print('3. vrstva',x.shape)
        # x = self.pool(F.elu(self.conv4(x)))
        # print('4. vrstva',x.shape)
        # x = torch.flatten(x, 1) # flatten all 
        x = x.view(x.size(0), -1)
        # print('po flatten', x.shape)
        x = torch.sigmoid(self.fc1(x))
        x = self.fc2(x)
        return x

In [79]:
net = Net()

# If we want to train the network from the beginning, we must also run next code cell

In [80]:
# Creation of indexes
indexes = mix_data(uad)
indexes = np.reshape(indexes, (173, -1))
indexes = torch.Tensor(indexes).int()

# Saving of created indexes
torch.save(indexes, '/content/drive/My Drive/artificial/indexes.pt')

# Saving of zero number of chunk
number = 0
torch.save(number, '/content/drive/My Drive/artificial/numberOfChunk.pt')

# Saving a base modes
torch.save(net.state_dict(), "/content/drive/My Drive/artificial/modelka.pth")

# Next part of the code is always run, regardless of the type of network training

In [81]:
# Loading a model
net.load_state_dict(torch.load("/content/drive/My Drive/artificial/modelka.pth"))
net.eval()

# Loading indexes
indexes = torch.load('/content/drive/My Drive/artificial/indexes.pt')

# Loading a number og chunk
number = torch.load('/content/drive/My Drive/artificial/numberOfChunk.pt')

In [82]:
# Definition of a Loss function and optimizer
loss_epoch = nn.MSELoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

In [83]:
# Print model's state_dict
print("Model's state_dict:")
for param_tensor in net.state_dict():
    print(param_tensor, "\t", net.state_dict()[param_tensor].size())

# Print optimizer's state_dict
print("Optimizer's state_dict:")
for var_name in optimizer.state_dict():
    print(var_name, "\t", optimizer.state_dict()[var_name])

Model's state_dict:
conv1.weight 	 torch.Size([8, 1, 5, 5])
conv1.bias 	 torch.Size([8])
conv2.weight 	 torch.Size([16, 8, 5, 5])
conv2.bias 	 torch.Size([16])
conv3.weight 	 torch.Size([32, 16, 5, 5])
conv3.bias 	 torch.Size([32])
fc1.weight 	 torch.Size([256, 512])
fc1.bias 	 torch.Size([256])
fc2.weight 	 torch.Size([1, 256])
fc2.bias 	 torch.Size([1])
Optimizer's state_dict:
state 	 {}
param_groups 	 [{'lr': 0.001, 'momentum': 0.9, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'params': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]}]


In [84]:
# sent network to the device
net.to(device)

Net(
  (conv1): Conv2d(1, 8, kernel_size=(5, 5), stride=(1, 1))
  (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(8, 16, kernel_size=(5, 5), stride=(1, 1))
  (conv3): Conv2d(16, 32, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=512, out_features=256, bias=True)
  (fc2): Linear(in_features=256, out_features=1, bias=True)
)

# Training og the network

In [85]:
# number = 0
indexes = [[0,0,0]]
# print(indexes[0])
# start = torch.cuda.Event(enable_timing=True)
# end = torch.cuda.Event(enable_timing=True)

# start.record()

patien = 0
patien_flag = 0

if device.__eq__('cuda:0'):
  for epoch in range(500):  # loop over the dataset multiple times
    number = torch.load('/content/drive/My Drive/artificial/numberOfChunk.pt')
    for k in range(number, len(indexes)):
      torch.save(k, '/content/drive/My Drive/artificial/numberOfChunk.pt')
      chunk, reference = generate_chunk(indexes[0][1], uad)
      torch.save(reference, '/content/drive/My Drive/artificial/lastChunkRefer.pt')
      running_loss = 0.0
      for i in range(0, len(chunk)):
        # get the inputs; data is a list of [inputs, labels]
        inputs, labels = chunk[i], reference[i]
        # to float ref
        print(len(labels))
        print(inputs.shape)
        labels = list(map(float, labels))
        # to tensor ref
        torch.save(labels, '/content/drive/My Drive/artificial/lastLabels.pt')
        labels = torch.FloatTensor(labels)
        # labels = hot(labels)
        # labels = labels.type(torch.LongTensor)
        labels = labels.to(device)
        # add new dimension
        inputs = inputs[None,:,:,:]
        inputs = torch.permute(inputs, (1,0,2,3))
        inputs = inputs.to(device)
        # print(inputs.dtype)
        # zero the parameter gradients
        optimizer.zero_grad()

        # forward + backward + optimize
        outputs = net(inputs)
        loss = loss_epoch(outputs, labels)
        loss.backward()

        torch.nn.utils.clip_grad_norm_(net.parameters(), 5)
        optimizer.step()
        running_loss += loss.item()
      print(f'[{epoch + 1}, {len(chunk)}] loss: {running_loss / len(chunk)}')
      if patien_flag < (running_loss/len(chunk)):
        patien = patien + 1
      patien_flag = running_loss / len(chunk)
      if patien == 5 or int(running_loss/len(chunk))==0:
        break
    if patien == 5 or int(running_loss/len(chunk))==0:
      break
      
    k = 0
    torch.save(k, '/content/drive/My Drive/artificial/numberOfChunk.pt')
    torch.save(net.state_dict(), "/content/drive/My Drive/artificial/modelka.pth")
  print('Finished Training')
else:
  print('Traning wasnt started, due to unavailabile cuda device')

# end.record()

100
torch.Size([100, 64, 62])
[1, 1] loss: 2506.498779296875
100
torch.Size([100, 64, 62])
[2, 1] loss: 2501.538330078125
100
torch.Size([100, 64, 62])
[3, 1] loss: 2492.11083984375
100
torch.Size([100, 64, 62])
[4, 1] loss: 2478.652099609375
100
torch.Size([100, 64, 62])
[5, 1] loss: 2461.541015625
100
torch.Size([100, 64, 62])
[6, 1] loss: 2441.099853515625
100
torch.Size([100, 64, 62])
[7, 1] loss: 2417.595703125
100
torch.Size([100, 64, 62])
[8, 1] loss: 2391.235595703125
100
torch.Size([100, 64, 62])
[9, 1] loss: 2362.154296875
100
torch.Size([100, 64, 62])
[10, 1] loss: 2330.44580078125
100
torch.Size([100, 64, 62])
[11, 1] loss: 2296.1728515625
100
torch.Size([100, 64, 62])
[12, 1] loss: 2259.377197265625
100
torch.Size([100, 64, 62])
[13, 1] loss: 2220.108642578125
100
torch.Size([100, 64, 62])
[14, 1] loss: 2178.445068359375
100
torch.Size([100, 64, 62])
[15, 1] loss: 2134.52587890625
100
torch.Size([100, 64, 62])
[16, 1] loss: 2088.58935546875
100
torch.Size([100, 64, 62])
[1

# Upload development data

In [86]:
paths_file = "/content/drive/My Drive/artificial/pathsToDevelopSounds.txt"
references = "/content/drive/My Drive/artificial/developRef.txt"

spectrogram = torchaudio.transforms.MelSpectrogram(
    sample_rate=SAMPLE_RATE,
    n_fft=nFFt,
    win_length = winLength,
    hop_length = hopLength,
    n_mels = nMels,
    power=1,
    normalized=True
)

develop_uad = UploadArtificialDataset(paths_file, references, spectrogram, SAMPLE_RATE, device)

print(f"There are {len(develop_uad)} samples in the dataset.")
signal, ref = develop_uad[7924]
print(signal.shape)
print(ref)

There are 10272 samples in the dataset.
torch.Size([1, 64, 876])
['-1.2', '-0.5', '2.4', '-1.1', '-1.8', '-3.1', '3.1', '-1', '1.4', '0.6', '-3.8', '-4.6', '3.1', '2.4']


# Prepare&Predict functions

In [87]:
# preparation function
def prepare_data(signal):
  len = int(signal.shape[2]/int(16000 / hopLength))
  prepared = torch.zeros(len, nMels, int(16000 / hopLength))
  move = 0
  for k in range(len):
    prepared[k] = signal[:, 0:nMels, 0+move:int(16000 / hopLength)+move]
    move = move + int(16000 / hopLength)
  prepared = prepared[None,:,:,:]
  prepared = torch.permute(prepared, (1,0,2,3))
  return prepared

# # ONE SECOND preparation
# def prepare_data(signal):
#   len = int(signal.shape[2]/int(16000 / hopLength))
#   prepared = torch.zeros(len, nMels, int(16000 / hopLength))
#   move = 0
#   for k in range(len):
#     prepared[k] = signal[:, 0:nMels, 0:int(16000 / hopLength)]
#   prepared = prepared[None,:,:,:]
#   prepared = torch.permute(prepared, (1,0,2,3))
#   return prepared


# prediction function
def predict(model, input, target):
    model.eval()
    with torch.no_grad():
        prediction = model(input)
    return prediction

# Testing of trained network

❗️**NEED TO BE MODIFIED**❗️

In [88]:
def do_prediction(ind):
  s, r = develop_uad[ind]
  s = prepare_data(s)
  s = s.to(device)

  r = list(map(float, r))
  r = torch.FloatTensor(r)
  print(r)
  r = r.to(device)

  return predict(net, s, r)

development_indexes = indexes[0]
for i in development_indexes[0:50]:
  print('-------------', i, '-------------')
  prediction = do_prediction(i).tolist()
  prediction = np.reshape(prediction, (1, -1))[0]
  prediction = torch.Tensor(prediction)
  print(prediction)

------------- 0 -------------
tensor([50., 50., 50., 50.])
tensor([50.2282, 50.2243, 50.2212, 50.2198])
------------- 0 -------------
tensor([50., 50., 50., 50.])
tensor([50.2282, 50.2243, 50.2212, 50.2198])
------------- 0 -------------
tensor([50., 50., 50., 50.])
tensor([50.2282, 50.2243, 50.2212, 50.2198])


# GitHub access 

In [20]:
%cd /content/drive/MyDrive/artificial/
# Create NEW EMPTY folder
# !git init vik_prj
%cd vik_prj/

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/artificial
/content/drive/MyDrive/artificial/vik_prj


In [21]:
%ls -a .git/

branches/  config  description  HEAD  hooks/  info/  objects/  refs/


In [22]:
!git status

On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	clear_project.ipynb

nothing added to commit but untracked files present (use "git add" to track)


In [23]:
!git add .

In [24]:
!git commit -m "Beautifully structured code cells"

[master (root-commit) df93c3f] Beautifully structured code cells
 1 file changed, 1 insertion(+)
 create mode 100644 clear_project.ipynb


In [25]:
!git config --global user.email "viktoriia.sergeeva@tul.cz"
!git config --global user.name "ViktoriiaSr"

In [26]:
username = "ViktoriiaSr"
repository = "vir_prj"
git_token = "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"

In [27]:
!git remote add origin https://{git_token}@github.com/{username}/{repository}.git
!git remote -v

origin	https://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@github.com/ViktoriiaSr/vir_prj.git (fetch)
origin	https://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@github.com/ViktoriiaSr/vir_prj.git (push)


In [28]:
!git push -u origin master

Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 5.71 KiB | 1.90 MiB/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To https://github.com/ViktoriiaSr/vir_prj.git
 * [new branch]      master -> master
Branch 'master' set up to track remote branch 'master' from 'origin'.
